language: ruby
dist: xenial
services: mysql
bundler_args: "--without deployment"
cache:
  bundler: true
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- bundle exec rake db:create
- bundle exec rake db:schema:load
script:
- bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
before_deploy: "./compile-build"
deploy:
  provider: releases
  api_key:
    secure: WklMhG2rAihfH9vdVbDnSmygFg/BcklUXS5KLWOGQKpNM5ZcGZ5ndZdmtmk8Qin5rxtjkNCTxczaH7kWXKFU+LtE6mXkoEG2zV7wTwSl/zbumoCbi9gHpOCcyf4qvam8n3iKOXRH+efJO0ulegD0O0iyyV7SXkamnXZR9GTEFpM=
  file: release.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: sanger/asset_audits
  name: $TRAVIS_TAG
notifications:
  slack:
    secure: jRpuqQALhIy3bC/GKNPkoPt0GKPiXamWRxaQD8XaebKfrYrB7+TecU4YR+nFpRqB8JGZVQUnOoCtQzH35zNNfxIS7D6RLGIDNPBiY8QRa9s6WdbKSVdKmd44al4MqtWc/7WE8w+gBe8mACovj9aeM9WnAk8UyxISAxgVfTEmTu8=

